In [1]:
#Creating a Numpy Array 
#Python program for Creation of Arrays
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
print(type(arr))
 
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
<class 'numpy.ndarray'>
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [26]:
#Accessing the array Index
# Python program to demonstrate
# indexing in numpy array
import numpy as np
 
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)
 
# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[::2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)
 
# Printing elements at
# specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)

Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.   0. ]
 [ 2.6  7. ]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [38]:
#Constructing a Datatype Object
# Python Program to create a data type object
import numpy as np
 
# Integer datatype
# guessed by Numpy
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)         
 
# Float datatype
# guessed by Numpy
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  
 
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)

Integer Datatype: 
int32

Float Datatype: 
float64

Forcing a Datatype: 
int64


In [49]:


# Python Program illustrating 
# numpy.ones method 
  
import numpy as np 
  
b = np.ones(2, dtype = int) 
print("Matrix b : \n", b) 
  
a = np.ones([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  
c = np.ones([3, 3]) 
print("\nMatrix c : \n", c) 


Matrix b : 
 [1 1]

Matrix a : 
 [[1 1]
 [1 1]]

Matrix c : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [88]:
#Math Operations on DataType array
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)
 
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)
 
 # using sum(axis=0) to print summation of all columns of matrix 
print ("The column wise summation of all matrix  is : ") 
print (np.sum(arr1,axis=0)) 
  
# using sum(axis=1) to print summation of all columns of matrix 
print ("The row wise summation of all matrix  is : ") 
print (np.sum(arr1,axis=1)) 

# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)
 
# Transpose of Array
# using In-built function 'T'
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)

# using multiply() to multiply matrices element wise 
print ("The element wise multiplication of matrix is : ") 
print (np.multiply(arr1,arr2)) 
  
# using dot() to multiply matrices 
print ("The product of matrices is : ") 
print (np.dot(arr1,arr2)) 



Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]

Addition of Array elements: 
19.0
The column wise summation of all matrix  is : 
[ 6. 13.]
The row wise summation of all matrix  is : 
[11.  8.]

Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]

Transpose of Array: 
[[4. 2.]
 [7. 6.]]
The element wise multiplication of matrix is : 
[[12. 42.]
 [ 4. 48.]]
The product of matrices is : 
[[26. 80.]
 [18. 60.]]


In [97]:
#sort array

print("Sorted array \n",np.sort(arr1,axis=None))

#sort array row wise

print("Sort row wise \n ",np.sort(arr1,axis=1))

#sort array by specific type

print("Sort by mergesort \n",np.sort(arr1,axis=0,kind='heapsort'))

Sorted array 
 [2. 4. 6. 7.]
Sort row wise 
  [[4. 7.]
 [2. 6.]]
Sort by mergesort 
 [[2. 6.]
 [4. 7.]]


In [98]:
#Array creation using numpy methods
#numpy.empty(shape, dtype = float, order = ‘C’) : 
#Return a new array of given shape and type, with random values.
import numpy as np
 
b = np.empty(2, dtype = int)
print("Matrix b : \n", b)
 
a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = np.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [         0 1075576832]

Matrix a : 
 [[         0 1075314688]
 [         0 1075576832]]

Matrix c : 
 [[0.22039774 0.42995636 0.6183698 ]
 [0.77637192 0.8961922  0.9719379 ]
 [0.99988386 0.9786557  0.90929743]]


In [99]:
#numpy.zeros(shape, dtype = None, order = ‘C’) : Return a new array of given shape and type, with zeros.
import numpy as np
 
b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)
 
a = np.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = np.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [105]:
#numpy.reshape(array, shape, order = ‘C’) : 
#Shapes an array without changing data of array.
 
import numpy as np
 
array = np.arange(8)
print("Original array : \n", array)
 
# shape array with 2 rows and 4 columns
array = np.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# shape array with 2 rows and 4 columns
array = np.arange(8).reshape(4 ,2)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# Constructs 3D array
array = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [106]:
#arange([start,] stop[, step,][, dtype]) : 
#Returns an array with evenly spaced elements as per the interval. 
#The interval mentioned is half opened i.e. [Start, Stop)

import numpy as np
 
print("A\n", np.arange(4).reshape(2, 2), "\n")
 
print("A\n", np.arange(4, 10), "\n")
 
print("A\n", np.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



In [110]:
#numpy.linspace(start, stop, num = 50, endpoint = True,
# retstep = False, dtype = None) :
# Returns number spaces evenly w.r.t interval.
# Similiar to arange but instead of step it uses sample number.
import numpy as np
 
# restep set to True
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n")
 
# To evaluate sin() in long range 
x = np.linspace(0, 2, 10)
print(x)
print("A\n", np.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]
A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [113]:
#numpy.ndarray.flatten(order = ‘C’) : 
#Return a copy of the array collapsed into one dimension.

import numpy as np
 
array = np.array([[1, 2], [3, 4]])
print(array)
 
# using flatten method
print(array.flatten())


[[1 2]
 [3 4]]
[1 2 3 4]


In [114]:
import numpy as np

a=np.array([1,2,5,3])

print("Adding 1 to array", a+1)

print("subtracting 3 from array", a-3)

print("Multiplying by 10", a*10)

print("Multiplying by 10", a**2)

Adding 1 to array [2 3 6 4]
subtracting 3 from array [-2 -1  2  0]
Multiplying by 10 [10 20 50 30]
Multiplying by 10 [ 1  4 25  9]
